repos:
  -   repo: local
      hooks:
        -   id: test_cases
            name: test_cases
            entry: python -m test
            language: system
            types: [python]
            verbose: true
