repos:
  -   repo: local
      hooks:
        -   id: test_cases
            name: test_cases
            entry: python hooks/test.py
            language: python
            verbose: true
            always_run: true
